"""
Ollama Model Deployer

Deploys fine-tuned models to Ollama using native safetensors import + quantization:
1. Creates Modelfile pointing to merged safetensors directory
2. Runs `ollama create --quantize q4_K_M` via docker exec
3. Verifies deployment
"""

import logging
import shutil
import subprocess
import requests
from pathlib import Path

logger = logging.getLogger(__name__)


class OllamaDeployer:
    """Deploy fine-tuned models to Ollama using native import."""

    def __init__(self, ollama_base_url: str = "http://llm-ollama:11434"):
        self.ollama_base_url = ollama_base_url
        self.ollama_api = f"{ollama_base_url}/api"

    def deploy_model(
        self,
        merged_model_path: str,
        model_name: str = "gpt-oss:20b",
        checkpoint_id: str = None,
    ) -> bool:
        """
        Deploy a merged HuggingFace model to Ollama.

        Ollama natively imports safetensors and quantizes via --quantize flag.

        Args:
            merged_model_path: Path to merged safetensors model directory
            model_name: Ollama model name to create/replace
            checkpoint_id: Optional checkpoint ID for tracking
        """
        try:
            logger.info(f"Deploying {model_name} from {merged_model_path}")

            # Create Modelfile
            modelfile_path = self._create_modelfile(merged_model_path, model_name, checkpoint_id)

            # Unload existing model
            self._unload_model(model_name)

            # Create model with native quantization
            success = self._create_ollama_model(modelfile_path, model_name)

            if success:
                logger.info("=" * 60)
                logger.info(f"OLLAMA DEPLOYMENT SUCCESSFUL: {model_name}")
                logger.info(f"Checkpoint: {checkpoint_id}")
                logger.info("=" * 60)
                self._verify_model(model_name)
            else:
                logger.error(f"OLLAMA DEPLOYMENT FAILED for {model_name}")

            # Clean up Modelfile
            modelfile_dir = Path(modelfile_path).parent
            if modelfile_dir.exists() and modelfile_dir.name.startswith("modelfile_"):
                shutil.rmtree(modelfile_dir, ignore_errors=True)

            return success

        except Exception as e:
            logger.error(f"Deployment error: {e}", exc_info=True)
            return False

    def _create_modelfile(self, merged_model_path: str, model_name: str, checkpoint_id: str) -> str:
        """Create Ollama Modelfile pointing to safetensors directory."""
        modelfile_dir = Path("/checkpoints") / f"modelfile_{checkpoint_id or 'tmp'}"
        modelfile_dir.mkdir(parents=True, exist_ok=True)
        modelfile_path = modelfile_dir / "Modelfile"

        modelfile_content = f"""# Fine-tuned {model_name}
# Checkpoint: {checkpoint_id}
# Auto-generated by RLHFL trainer

FROM {merged_model_path}
"""
        modelfile_path.write_text(modelfile_content)
        logger.info(f"Created Modelfile: {modelfile_path}")
        return str(modelfile_path)

    def _create_ollama_model(self, modelfile_path: str, model_name: str) -> bool:
        """Create/replace Ollama model with native quantization."""
        try:
            logger.info(f"Creating Ollama model: {model_name} (with Q4_K_M quantization)")

            cmd = [
                "docker", "exec", "llm-ollama",
                "ollama", "create",
                "--quantize", "q4_K_M",
                model_name,
                "-f", modelfile_path,
            ]

            logger.info(f"Running: {' '.join(cmd)}")
            result = subprocess.run(
                cmd,
                check=True,
                capture_output=True,
                text=True,
                timeout=1800,  # 30 minute timeout for quantization
            )

            logger.info(f"ollama create output: {result.stdout}")
            if result.stderr:
                logger.warning(f"ollama create stderr: {result.stderr}")

            return True

        except subprocess.CalledProcessError as e:
            logger.error(f"ollama create failed: {e.stderr}")
            return False
        except subprocess.TimeoutExpired:
            logger.error("ollama create timed out (30 min)")
            return False
        except Exception as e:
            logger.error(f"Unexpected error during model creation: {e}")
            return False

    def _unload_model(self, model_name: str) -> None:
        """Force unload a model from Ollama memory."""
        try:
            response = requests.post(
                f"{self.ollama_api}/unload",
                json={"name": model_name},
                timeout=30,
            )
            if response.status_code == 200:
                logger.info(f"Model {model_name} unloaded")
            else:
                logger.debug(f"Unload response: {response.status_code}")
        except requests.exceptions.RequestException:
            pass  # Best-effort

    def _verify_model(self, model_name: str) -> bool:
        """Verify the model is available in Ollama."""
        try:
            response = requests.get(f"{self.ollama_api}/tags", timeout=10)
            response.raise_for_status()
            models = response.json().get("models", [])
            model_names = [m.get("name") for m in models]
            if model_name in model_names:
                logger.info(f"Model {model_name} verified in Ollama")
                return True
            logger.warning(f"Model {model_name} not found in Ollama tags")
            return False
        except Exception as e:
            logger.warning(f"Failed to verify model: {e}")
            return False

    def update_config_pointer(self, model_name: str) -> bool:
        """Update system config to point to the new model."""
        try:
            import yaml
            config_path = Path("/config/system_config.yaml")
            if not config_path.exists():
                return False

            with open(config_path) as f:
                config = yaml.safe_load(f)

            old_model = config.get("llm_proxy", {}).get("external_model_name")
            config.setdefault("llm_proxy", {})["external_model_name"] = model_name

            with open(config_path, "w") as f:
                yaml.dump(config, f, default_flow_style=False, sort_keys=False)

            logger.info(f"Config updated: {old_model} -> {model_name}")
            return True
        except Exception as e:
            logger.error(f"Failed to update config: {e}")
            return False

    def rotate_checkpoints(self, keep_count: int = 3) -> None:
        """Keep only the N most recent checkpoint directories."""
        try:
            checkpoints_dir = Path("/checkpoints")
            if not checkpoints_dir.exists():
                return

            checkpoints = sorted(
                [d for d in checkpoints_dir.iterdir()
                 if d.is_dir() and d.name.startswith("checkpoint_")],
                key=lambda x: x.stat().st_mtime,
                reverse=True,
            )

            to_delete = checkpoints[keep_count:]
            for checkpoint in to_delete:
                logger.info(f"Removing old checkpoint: {checkpoint.name}")
                shutil.rmtree(checkpoint)

            if to_delete:
                logger.info(f"Cleaned up {len(to_delete)} old checkpoints")
        except Exception as e:
            logger.warning(f"Checkpoint rotation failed: {e}")

    def list_models(self) -> list:
        """List all models in Ollama."""
        try:
            response = requests.get(f"{self.ollama_api}/tags", timeout=10)
            response.raise_for_status()
            return response.json().get("models", [])
        except Exception as e:
            logger.error(f"Failed to list models: {e}")
            return []
